@startuml
interface Iterable<T>{
 Iterator<E>
 }

interface Collection<E> extends Iterable
abstract class AbstractCollection<E> implements Collection
interface List<E> extends Collection
abstract class AbstractList<E> implements List

@enduml