@startuml
interface List<E> {
List
size
isEmpty
contains
iterator
toArray
toArray
add
remove
containsAll
addAll
addAll
removeAll
retainAll
replaceAll
sort
clear
equals
hashCode
get
set
add
remove
indexOf
lastIndexOf
listIterator
listIterator
subList
spliterator
}

@enduml